name: Trigger Start Stop Instance

on:
  schedule:
    - cron: '0 0 * * 1'
    - cron: '0 17 * * 5'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to trigger
        shell: bash
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl --location 'https://oci-jobmanager.wcydtt.co/status' \
            --header 'x-api-key: 2353c92ba586c91cffa674d2b6bfda81174f99e38fac144ba45a394ae6d55d9d' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json'