name: 'Auto Assign'
on:
  pull_request:
    branches: [master]

jobs:
  checkout:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5